### ISSUE TITLE
xcode 8.3 swift 3 warnings

### ISSUE THREAD

**Issue by alexookah** [Alterplay/APKenBurnsView#5]
There are warnings in the latest xcode 8.3:

FacesDrawer.swift:30:23: 'global(priority:)' was deprecated in iOS 8.0
FacesDrawer.swift:30:74: 'default' was deprecated in iOS 8.0: Use qos attributes instead

`        DispatchQueue.global(priority: DispatchQueue.GlobalQueuePriority.default).async {
`

RuntimeProperties.swift:21:33: Conditional cast from 'T' to 'AnyObject' always succeeds

```
func setAssociatedObject<T>(_ object: AnyObject, value: T, associativeKey: UnsafeRawPointer, policy: objc_AssociationPolicy) {
    if let v: AnyObject = value as? AnyObject {
```

**Comment by NickolaySheika** [comment]
APKenBurnsView doesn't support Swift 3.
